build:
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false
  checkExhaustiveness: false
  # when writing own rules with new properties, exclude the property path e.g.: 'my_rule_set,.*>.*>[my_property]'
  excludes: ''

complexity:
  active: true
  NamedArguments:
    active: true
    threshold: 4
  ComplexCondition:
    threshold: 5
  LongParameterList:
    functionThreshold: 7
  CyclomaticComplexMethod:
    active: false
  CognitiveComplexMethod:
    active: true
    threshold: 16
  StringLiteralDuplication:
    active: false

performance:
  active: true
  ArrayPrimitive:
    active: true
  CouldBeSequence:
    active: true
  ForEachOnRange:
    active: true
  UnnecessaryPartOfBinaryExpression:
    active: true
  UnnecessaryTemporaryInstantiation:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: false

style:
#  UnusedImports:
#    active: true
  MagicNumber:
    active: false
  ReturnCount:
    active: true
    excludeGuardClauses: true
    max: 4
  LoopWithTooManyJumpStatements:
    active: true
    maxJumpCount: 3
  WildcardImport:
    active: false
  ForbiddenComment:
    active: false
  UnusedPrivateProperty:
    allowedNames: '_|ignored|expected|serialVersionUID|.+Handler\d*|repeatable'
  ForbiddenMethodCall:
    active: true
  BracesOnIfStatements:
    active: true
    singleLine: 'never'
    multiLine: 'always'
